export const temporaryData = [
  {
    id: "1",
    img: "/images/car-card/img1.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
  },
  {
    id: "2",
    img: "/images/car-card/img2.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
  },
  {
    id: "3",
    img: "/images/car-card/img3.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
  },
  {
    id: "4",
    img: "/images/car-card/img4.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
  },
  {
    id: "5",
    img: "/images/car-card/img1.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
  },
];
