export const temporaryData = [
  {
    id: "1",
    img: "/images/car-card/img1.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "cars",
    reserved: true
  },
  {
    id: "2",
    img: "/images/car-card/img2.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "bakkie",
  },
  {
    id: "3",
    img: "/images/car-card/img3.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0100,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "commercial",
  },
  {
    id: "4",
    img: "/images/car-card/img4.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0101,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "commercial",
  },
  {
    id: "5",
    img: "/images/car-card/img1.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "commercial",
  },
  {
    id: "6",
    img: "/images/car-card/img1.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "cars",
  },
  {
    id: "7",
    img: "/images/car-card/img2.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "bakkie",
  },
  {
    id: "8",
    img: "/images/car-card/img3.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "commercial",
  },
  {
    id: "9",
    img: "/images/car-card/img4.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "commercial",
  },
  {
    id: "10",
    img: "/images/car-card/img1.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "commercial",
  },
  {
    id: "11",
    img: "/images/car-card/img1.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "cars",
  },
  {
    id: "12",
    img: "/images/car-card/img2.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "bakkie",
  },
  {
    id: "13",
    img: "/images/car-card/img3.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "commercial",
  },
  {
    id: "14",
    img: "/images/car-card/img4.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "commercial",
  },
  {
    id: "15",
    img: "/images/car-card/img1.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "commercial",
  },
  {
    id: "16",
    img: "/images/car-card/img1.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "cars",
  },
  {
    id: "17",
    img: "/images/car-card/img2.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "bakkie",
  },
  {
    id: "18",
    img: "/images/car-card/img3.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "commercial",
  },
  {
    id: "19",
    img: "/images/car-card/img4.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "commercial",
  },
  {
    id: "20",
    img: "/images/car-card/img1.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "commercial",
  },
  {
    id: "21",
    img: "/images/car-card/img1.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "cars",
  },
  {
    id: "22",
    img: "/images/car-card/img2.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "bakkie",
  },
  {
    id: "23",
    img: "/images/car-card/img3.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "commercial",
  },
  {
    id: "24",
    img: "/images/car-card/img4.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "commercial",
  },
  {
    id: "25",
    img: "/images/car-card/img1.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "commercial",
  },
  {
    id: "26",
    img: "/images/car-card/img1.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "cars",
  },
  {
    id: "27",
    img: "/images/car-card/img2.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "bakkie",
  },
  {
    id: "28",
    img: "/images/car-card/img3.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "commercial",
  },
  {
    id: "29",
    img: "/images/car-card/img4.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0139,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "commercial",
  },
  {
    id: "30",
    img: "/images/car-card/img1.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "commercial",
  },
  {
    id: "31",
    img: "/images/car-card/img1.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0109,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "commercial",
  },
  {
    id: "32",
    img: "/images/car-card/img1.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0140,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "commercial",
  },
  {
    id: "33",
    img: "/images/car-card/img1.png",
    year: 2012,
    make: "Volkswagen",
    model: "Polo Hatch",
    price: "R\u00A0120,900",
    mileage: "27200km",
    transmission: "manual",
    href: "/",
    type: "commercial",
  },
];
