// const makes = [
//     "Acura",
//     "Alfa Romeo",
//     "Audi",
//     "BMW",
//     "Cadillac",
//     "Chevrolet",
//     "Chrysler",
//     "Citroën",
//     "Dodge",
//     "Fiat",
//     "Genesis",
//     "GMC",
//     "Honda",
//     "Hyundai",
//     "Infiniti",
//     "Jaguar",
//     "Jeep",
//     "Kia",
//     "Land Rover",
//     "Lexus",
//     "Mercedes-Benz",
//     "Mini",
//     "Mitsubishi",
//     "Nissan",
//     "Opel",
//     "Peugeot",
//     "Porsche",
//     "Renault",
//     "Rolls-Royce",
//     "Saab",
//     "Škoda",
//     "Subaru",
//     "Suzuki",
//     "Tesla",
//     "Toyota",
//     "Volkswagen",
//     "Volvo"
// ];

const makes = [
    "Toyota",
    "Nissan",
    "Ford",
    "Audi",
    "BMW",
    "Volkswagen",
    "JAC",
    "Kia",
    "Peugeot",
    "Honda",
    "Mercedes-Benz",
    "Daihatsu",
    "Datsun",
    "Suzuki",
    "Opel",
    "Jaguar",
    "Fiat",
    "GWM",
    "Hyundai",
    "MINI",
    "Lexus",
    "Daewoo",
    "Mitsubishi",
    "Renault",
    "Subaru",
    "Chery",
    "BAIC",
    "Chevrolet",
    "Mazda"
];

export default makes;
